ItemStore/ItemStore/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ItemStore.Models
{
    [Table("Categories", Schema = "dbo")]
    public class Category
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Required(ErrorMessage = "No category name inserted")]
        public string name { get; set; }


        public virtual ICollection<ItemType> ItemType { get; set; }

    }
}

ItemStore/ItemStore/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ItemStore.Models;
using PagedList;
namespace ItemStore.Controllers
{
    [HandleError]
    public class CategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index(string search, int? i)
        {

            List<Category> categories = db.Categories.ToList();
            return View(db.Categories.Where(x=>x.name.StartsWith(search) || search == null).ToList().ToPagedList(i ?? 1,3));
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "id,name")]Category categories)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(categories);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categories);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category categories = db.Categories.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "id,name")] Category categories)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categories).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categories);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category categories = db.Categories.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Category categories = db.Categories.Find(id);
            db.Categories.Remove(categories);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ItemStore/ItemStore/Controllers/ItemTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dropbox.Api;
using Dropbox.Api.Files;
using ItemStore.Models;
using PagedList;

namespace ItemStore.Controllers
{
    [HandleError]
    public class ItemTypeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(string search, int? i,int categoryId)
        {
            var category = db.Categories.Find(categoryId);
            if (category != null)
            {
                ViewBag.category = category;
                var list = search == null ? db.ItemTypes.Where(x => x.categoryId == categoryId) : db.ItemTypes.Where(x => x.name.StartsWith(search) && x.categoryId == categoryId);
                return View(list.ToList().ToPagedList(i ?? 1, 3));
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create(int id)
        {
            CategoryId = id;
            return View();
        }

        private static int CategoryId = -1;

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(HttpPostedFileBase file, [Bind(Include = "id,name,imageUrl,categoryId")] ItemType itemType)
        {
            string ApplicationName = "ItemStore";
            string accessToken = "cyl3tGx0a0AAAAAAAAAADHdErHVnqXHswLIFPd9o9FtpphheplFaYsAQrmMS1tqh";

            using (DropboxClient client = new DropboxClient(accessToken, new DropboxClientConfig(ApplicationName)))
            {
                string[] spitInputFileName = file.FileName.Split(new string[] { "\\" }, StringSplitOptions.RemoveEmptyEntries);
                string fileNameAndExtension = spitInputFileName[spitInputFileName.Length - 1];

                string[] fileNameAndExtensionSplit = fileNameAndExtension.Split('.');
                string originalFileName = fileNameAndExtensionSplit[0];
                string originalExtension = fileNameAndExtensionSplit[1];

                if (originalExtension == "jpeg" || originalExtension == "png" || originalExtension == "jpg" || originalExtension == "gif")
                {
                    string fileName = @"/Images/" + originalFileName + Guid.NewGuid().ToString().Replace("-", "") + "." + originalExtension;

                    var updated = client.Files.UploadAsync(
                        fileName,
                        mode: WriteMode.Overwrite.Overwrite.Instance,
                        body: file.InputStream).Result;

                    var result = client.Sharing.CreateSharedLinkWithSettingsAsync(fileName).Result.Url;

                    itemType.categoryId = CategoryId;
                    itemType.imageURL = result;

                    db.ItemTypes.Add(itemType);
                    db.SaveChanges();

                    return RedirectToAction("index", new { categoryId = CategoryId });
                }
                else
                {
                    ViewBag.Message = "File must be an image!";
                    return View();
                }

            }
        }


 
    }
}

ItemStore/ItemStore/Views/Category/Create.cshtml
@model ItemStore.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>

        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ItemStore/ItemStore/Views/Category/Delete.cshtml
@model ItemStore.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ItemStore/ItemStore/Views/Category/Details.cshtml
@model ItemStore.Models.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ItemStore/ItemStore/Views/Category/Edit.cshtml
@model ItemStore.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ItemStore/ItemStore/Views/Category/Index.cshtml
@model IPagedList<ItemStore.Models.Category>
@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "Index";
}



<h2>Category</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

    <p>
        @using (Html.BeginForm("Index", "Category", FormMethod.Get))
        {
            <input type="text" name="search">
            <input type="submit" name="submit" value="Search">
        }
    </p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.name
            </td>

            @if (User.IsInRole("Admin"))
            {
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Add ItemType", "Index", "ItemType", new { categoryId = item.id }, null) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>
            }
            else
            {
                <td>
                    @Html.ActionLink("Add ItemType", "Index", "ItemType", new { categoryId = item.id }, null)
                </td>
            }
        </tr>
        }

</table>
<br />
@Html.PagedListPager(Model, i => Url.Action("Index","Category", new { i, search=Request.QueryString["search"]}))